// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

public partial class AdoptContext : DbContext
{
    public AdoptContext(DbContextOptions<AdoptContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tracker> Trackers { get; set; }

    public virtual DbSet<Visitor> Visitors { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tracker>(entity =>
        {
            entity.ToTable("Tracker");

            entity.Property(e => e.TrackerId).HasColumnName("TrackerID");
            entity.Property(e => e.City)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("city");
            entity.Property(e => e.Country)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("country");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Tracke__Creat__02A839AF")
                .HasColumnType("datetime");
            entity.Property(e => e.Hostname)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("hostname");
            entity.Property(e => e.Href)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("href");
            entity.Property(e => e.Ip)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ip");
            entity.Property(e => e.Loc)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("loc");
            entity.Property(e => e.Org)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("org");
            entity.Property(e => e.Postal)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("postal");
            entity.Property(e => e.Readme)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("readme");
            entity.Property(e => e.Referer)
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasColumnName("referer");
            entity.Property(e => e.Region)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("region");
            entity.Property(e => e.Timezone)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("timezone");
            entity.Property(e => e.Title)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("title");
        });

        modelBuilder.Entity<Visitor>(entity =>
        {
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(75)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}