// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Tracker
{
    public int TrackerId { get; set; }

    public string Ip { get; set; }

    public string Hostname { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public string Country { get; set; }

    public string Loc { get; set; }

    public string Org { get; set; }

    public string Postal { get; set; }

    public string Timezone { get; set; }

    public string Readme { get; set; }

    public string Referer { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Title { get; set; }

    public string Href { get; set; }
}