// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Visitor
{
    public int VisitorId { get; set; }

    public string Email { get; set; }

    public DateTime? CreatedDate { get; set; }
}